#[cfg(feature = "cffi")]
mod cffi {
    use std::{io::Write, path::Path};

    use build_info_build::semver;
    use cbindgen::{
        Config, ConstantConfig, EnumConfig, FunctionConfig, MacroExpansionConfig, RenameRule,
        StructConfig,
    };

    pub(super) fn main_cffi() {
        // Generate C header using cbindgen
        let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let output_file_path = Path::new(&crate_dir).join("include").join("hycore.h");

        let version = std::env::var("CARGO_PKG_VERSION").unwrap();
        let version = semver::Version::parse(&version).unwrap();

        let prefix = format!(
            "\n#define HY_VERSION_MAJOR {}\n\
               #define HY_VERSION_MINOR {}\n\
               #define HY_VERSION_PATCH {}\n\
               #define HY_VERSION \"{}\"\n\n\
               static const char *HY_LOGGER_PLUGIN_NAME = \"hycore::plugin::logger::LoggerPlugin\";",
            version.major,
            version.minor,
            version.patch,
            version.to_string(),
        );

        let file_header = format!(
            "/**
 * @file hycore.h
 * @brief Main C API header for Hyperion Core library.
 * @version {}.{}.{}
 *
 * This file header provides the C API for interacting with the Hyperion framework.
 * It was generated using cbindgen={}. DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is part of Hyperion.
 *
 * Copyright (C) 2024 Hyperion Project
 *
 * Hyperion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Hyperion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Hyperion. If not, see <https://www.gnu.org/licenses/>.
 */\n\n",
            version.major,
            version.minor,
            version.patch,
            cbindgen::VERSION
        );

        let bindings = cbindgen::Builder::new()
            .with_config(Config {
                language: cbindgen::Language::C,
                documentation: false,
                include_guard: Some("_HYCORE_H".to_string()),
                cpp_compat: true,
                tab_width: 2,
                style: cbindgen::Style::Type,
                constant: ConstantConfig {
                    allow_static_const: true,
                    ..Default::default()
                },
                structure: StructConfig {
                    rename_fields: RenameRule::CamelCase,
                    derive_constructor: true,
                    ..Default::default()
                },
                function: FunctionConfig {
                    rename_args: RenameRule::CamelCase,
                    ..Default::default()
                },
                enumeration: EnumConfig {
                    rename_variants: RenameRule::ScreamingSnakeCase,
                    add_sentinel: false,
                    prefix_with_name: true,
                    ..Default::default()
                },
                macro_expansion: MacroExpansionConfig { bitflags: true },
                ..Default::default()
            })
            .with_crate(crate_dir)
            .with_after_include(prefix)
            .include_item("HyLoggerPluginCreateInfo")
            .include_item("HyModuleCompileInfoFlagBits")
            .exclude_item("ModuleCompileInfoFlags")
            .with_braces(cbindgen::Braces::NextLine)
            .generate()
            .expect("Unable to generate bindings");

        // Create the directory if it doesn't exist
        std::fs::create_dir_all(output_file_path.parent().unwrap()).unwrap();
        let file = std::fs::File::create(output_file_path).unwrap();
        let mut writer = std::io::BufWriter::new(file);
        writer.write_all(file_header.as_bytes()).unwrap();
        bindings.write(&mut writer);
    }
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/");

    build_info_build::build_script();

    #[cfg(feature = "cffi")]
    cffi::main_cffi();
}
