[package]
name = "hycore"
version = "0.1.3"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
single_thread_cell = { workspace = true }
bevy_reflect = { workspace = true, features = ["auto_register_inventory"] }
bevy_ecs = { workspace = true, features = [
    "async_executor",
    "debug",
    "reflect_auto_register",
] }
hashbrown = { workspace = true }
bevy_tasks = { workspace = true }
thread_local = { workspace = true }
smallbox = { workspace = true }
anyhow = { workspace = true, features = ["backtrace"] }
hyinstr = { workspace = true, features = ["serde", "chumsky", "borsh"] }
uuid = { workspace = true, features = ["v4", "serde"] }
borsh = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
petgraph.workspace = true
smallvec.workspace = true
semver.workspace = true
parking_lot.workspace = true
crossbeam.workspace = true
build-info.workspace = true
bitflags = { workspace = true }
strum = { workspace = true, features = ["derive"] }
nalgebra = { workspace = true, features = ["sparse"] }
enum-map.workspace = true
either.workspace = true
slotmap.workspace = true
bit-set.workspace = true
toml.workspace = true
downcast-rs.workspace = true
chrono.workspace = true
inventory.workspace = true
zstd.workspace = true
dashmap.workspace = true
paste.workspace = true
pyo3 = { workspace = true, features = [
    "uuid",
    "extension-module",
    "abi3",
    "chrono",
], optional = true }
serde_json.workspace = true
async-io = { workspace = true, optional = true }

# cffi dependencies
libc = { workspace = true, optional = true }

[build-dependencies]
build-info-build.workspace = true
cbindgen = { version = "0.28", optional = true }

[features]
default = ["remote"]
pyo3 = ["dep:pyo3"]
cffi = ["dep:libc", "dep:cbindgen"]

remote = ["dep:async-io"]
