use std::io::Write;

use cbindgen::{Config, ConstantConfig};
use hycore::magic;

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_file = format!("{}/include/hycore.h", crate_dir);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/");
    let version = std::env::var("CARGO_PKG_VERSION").unwrap();
    let version = semver::Version::parse(&version).unwrap();

    let prefix = format!(
        "\n#define HY_VERSION_MAJOR {}\n\
           #define HY_VERSION_MINOR {}\n\
           #define HY_VERSION_PATCH {}\n\
           #define HY_LOGGER_NAME_EXT \"{}\"\n",
        version.major,
        version.minor,
        version.patch,
        magic::HYPERION_LOGGER_NAME_EXT,
    );
    let file_header = format!(
        "/**
 * @file hycore.h
 * @brief Main C API header for Hyperion Core library.
 * @version {}.{}.{}
 *
 * This file header provides the C API for interacting with the Hyperion framework.
 * It was generated using cbindgen={}. DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is part of Hyperion.
 *
 * Copyright (C) 2024 Hyperion Project
 *
 * Hyperion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Hyperion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Hyperion. If not, see <https://www.gnu.org/licenses/>.
 */\n\n",
        version.major,
        version.minor,
        version.patch,
        cbindgen::VERSION
    );

    let bindings = cbindgen::Builder::new()
        .with_config(Config {
            language: cbindgen::Language::C,
            documentation: true,
            documentation_style: cbindgen::DocumentationStyle::Doxy,
            include_guard: Some("_HYCORE_H".to_string()),
            cpp_compat: true,
            documentation_length: cbindgen::DocumentationLength::Full,
            tab_width: 2,
            constant: ConstantConfig {
                allow_static_const: true,
                ..Default::default()
            },
            ..Default::default()
        })
        .with_crate(crate_dir)
        .with_after_include(prefix)
        .with_braces(cbindgen::Braces::NextLine)
        .include_item("HyLogCreateInfoEXT")
        .generate()
        .expect("Unable to generate bindings");
    // bindings.write_to_file(output_file);
    let file = std::fs::File::create(output_file).unwrap();
    let mut writer = std::io::BufWriter::new(file);
    writer.write_all(file_header.as_bytes()).unwrap();
    bindings.write(&mut writer);
}
