use std::io::Write;

use cbindgen::{Config, ConstantConfig};
use hycore::magic;

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_file = format!("{}/include/hycore.h", crate_dir);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/");
    let version = std::env::var("CARGO_PKG_VERSION").unwrap();
    let version = semver::Version::parse(&version).unwrap();

    let prefix = format!(
        "\n#define HY_VERSION_MAJOR {}\n\
           #define HY_VERSION_MINOR {}\n\
           #define HY_VERSION_PATCH {}\n\
           #define HY_LOGGER_NAME_EXT \"{}\"\n",
        version.major,
        version.minor,
        version.patch,
        magic::HYPERION_LOGGER_NAME_EXT,
    );
    let file_header = format!(
        "/**\n\
         * @file hycore.h\n\
         * @brief Main C API header for Hyperion Core library.\n\
         * @version {}.{}.{}\n\
         *\n\
         * This file header provides the C API for interacting with the Hyperion framework.\n\
         * It was generated using cbindgen={}. DO NOT EDIT THIS FILE MANUALLY!\n\
         *\n\
         * This file is part of Hyperion.\n\
         *\n\
         * Copyright (C) 2024 Hyperion Project\n\
         *\n\
         * Hyperion is free software: you can redistribute it and/or modify\n\
         * it under the terms of the GNU General Public License as published by\n\
         * the Free Software Foundation, either version 3 of the License, or\n\
         * (at your option) any later version.\n\
         *\n\
         * Hyperion is distributed in the hope that it will be useful,\n\
         * but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
         * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n\
         * GNU General Public License for more details.\n\
         *\n\
         * You should have received a copy of the GNU General Public License\n\
         * along with Hyperion.  If not, see <https://www.gnu.org/licenses/>.\n\
         *\n\
         */\n\n",
        version.major,
        version.minor,
        version.patch,
        cbindgen::VERSION
    );

    let bindings = cbindgen::Builder::new()
        .with_config(Config {
            language: cbindgen::Language::C,
            documentation: true,
            documentation_style: cbindgen::DocumentationStyle::Doxy,
            include_guard: Some("_HYCORE_H".to_string()),
            cpp_compat: false,
            documentation_length: cbindgen::DocumentationLength::Full,
            tab_width: 2,
            constant: ConstantConfig {
                allow_static_const: true,
                ..Default::default()
            },
            ..Default::default()
        })
        .with_crate(crate_dir)
        .with_after_include(prefix)
        .with_braces(cbindgen::Braces::NextLine)
        .include_item("HyLogCreateInfoEXT")
        .generate()
        .expect("Unable to generate bindings");
    // bindings.write_to_file(output_file);
    let file = std::fs::File::create(output_file).unwrap();
    let mut writer = std::io::BufWriter::new(file);
    writer.write_all(file_header.as_bytes()).unwrap();
    bindings.write(&mut writer);
}
