/**
* @file hycore.h
* @brief Main C API header for Hyperion Core library.
* @version 0.1.1
*
* This file header provides the C API for interacting with the Hyperion framework.
* It was generated using cbindgen=0.27.0. DO NOT EDIT THIS FILE MANUALLY!
*
* This file is part of Hyperion.
*
* Copyright (C) 2024 Hyperion Project
*
* Hyperion is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* Hyperion is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Hyperion.  If not, see <https://www.gnu.org/licenses/>.
*
*/

#ifndef _HYCORE_H
#define _HYCORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define HY_VERSION_MAJOR 0
#define HY_VERSION_MINOR 1
#define HY_VERSION_PATCH 1
#define HY_LOGGER_NAME_EXT "__EXT_hyperion_logger"


enum HyLogLevelEXT
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus

{
  HY_LOG_LEVEL_TRACE = 0,
  HY_LOG_LEVEL_DEBUG = 1,
  HY_LOG_LEVEL_INFO = 2,
  HY_LOG_LEVEL_WARN = 3,
  HY_LOG_LEVEL_ERROR = 4,
};
#ifndef __cplusplus
typedef uint32_t HyLogLevelEXT;
#endif // __cplusplus

enum HyModuleSourceType
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus

{
  HY_MODULE_SOURCE_TYPE_ASSEMBLY,
};
#ifndef __cplusplus
typedef uint32_t HyModuleSourceType;
#endif // __cplusplus

enum HyResult
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus

{
  HY_RESULT_SUCCESS,
  HY_RESULT_INVALID_POINTER,
  HY_RESULT_IO_ERROR,
  HY_RESULT_OUT_OF_MEMORY,
  HY_RESULT_MANIFEST_PARSE_ERROR,
  HY_RESULT_UNKNOWN,
  HY_RESULT_PLUGIN_NOT_FOUND,
  HY_RESULT_UTF8_ERROR,
  HY_RESULT_INSTR_ERROR,
  HY_RESULT_KEY_NOT_FOUND,
  HY_RESULT_STRUCTURE_TYPE_MISMATCH,
};
#ifndef __cplusplus
typedef uint32_t HyResult;
#endif // __cplusplus

enum HyStructureType
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus

{
  HY_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
  HY_STRUCTURE_TYPE_APPLICATION_INFO,
  HY_STRUCTURE_TYPE_MODULE_COMPILE_INFO,
  HY_STRUCTURE_TYPE_MODULE_SOURCE_INFO,
  HY_STRUCTURE_TYPE_LOG_CREATE_INFO_EXT = 268435456,
};
#ifndef __cplusplus
typedef uint32_t HyStructureType;
#endif // __cplusplus

typedef struct HyInstance HyInstance;

typedef struct HyVersionInfo
{
  uint16_t major;
  uint16_t minor;
  uint16_t patch;
} HyVersionInfo;

typedef struct HyApplicationInfo
{
  HyStructureType sType;
  struct HyVersionInfo applicationVersion;
  const char *pApplicationName;
  struct HyVersionInfo engineVersion;
  const char *pEngineName;
} HyApplicationInfo;

typedef struct HyInstanceCreateInfo
{
  HyStructureType sType;
  const struct HyApplicationInfo *pApplicationInfo;
  const char *const *ppEnabledExtensions;
  uint32_t enabledExtensionsCount;
  uint32_t nodeId;
  void *pNext;
} HyInstanceCreateInfo;

typedef struct HyModuleSourceInfo
{
  HyStructureType sType;
  HyModuleSourceType sourceType;
  const char *filename;
  const uint8_t *data;
} HyModuleSourceInfo;

typedef struct HyModuleCompileInfo
{
  HyStructureType sType;
  const struct HyModuleSourceInfo *const *ppSources;
  uint32_t sourcesCount;
} HyModuleCompileInfo;

typedef struct HyLogMessageEXT
{
  HyLogLevelEXT level;
  int64_t timeStamp;
  const char *message;
  const char *module;
  const char *file;
  uint32_t line;
  const char *threadName;
  void *pNext;
} HyLogMessageEXT;

typedef void (*HyLogCallback_PFN)(struct HyLogMessageEXT *message);

typedef struct HyLogCreateInfoEXT
{
  HyStructureType sType;
  HyLogLevelEXT level;
  HyLogCallback_PFN callback;
  void *pNext;
} HyLogCreateInfoEXT;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Retrieves information about the version of the Hycore library.
 *
 * # Safety
 * - The `pVersionInfo` pointer must be a valid, non-null pointer to a `HyVersionInfo` struct.
 */
void hyGetVersionInfo(struct HyVersionInfo *pVersionInfo);

/**
 * Create an instance of the Hycore library.
 *
 * # Safety
 * - The `pInstanceCreateInfo` pointer must be a valid, non-null pointer to a `HyInstanceCreateInfo` struct.
 * - The `pInstance` pointer must be a valid, non-null pointer to a pointer to `HyInstance`.
 */
HyResult hyCreateInstance(const struct HyInstanceCreateInfo *pInstanceCreateInfo,
                          struct HyInstance **pInstance);

/**
 * Destroys an instance created by `hyCreateInstance`.
 *
 * # Safety
 * - The `instance` pointer must be a valid, non-null pointer to a `HyInstance`.
 */
void hyDestroyInstance(struct HyInstance *instance);

/**
 * Compile module sources into a binary format.
 *
 * # Safety
 * - The `instance` pointer must be a valid, non-null pointer to a `HyInstance`.
 * - The `pModuleCompileInfo` pointer must be a valid, non-null pointer to a `HyModuleCompileInfo`.
 * - The `ppDataPtr` and `pDataLen` pointers must be valid, non-null pointers to receive the output data. The caller is responsible for freeing the allocated data using `libc::free`.
 *
 */
HyResult hyCompileModule(const struct HyInstance *instance,
                         const struct HyModuleCompileInfo *pModuleCompileInfo,
                         uint8_t **ppDataPtr,
                         uint32_t *pDataLen);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _HYCORE_H */
