/**
 * @file hycore.h
 * @brief Main C API header for Hyperion Core library.
 * @version 0.1.3
 *
 * This file header provides the C API for interacting with the Hyperion framework.
 * It was generated using cbindgen=0.28.0. DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is part of Hyperion.
 *
 * Copyright (C) 2024 Hyperion Project
 *
 * Hyperion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Hyperion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Hyperion. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef _HYCORE_H
#define _HYCORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define HY_VERSION_MAJOR 0
#define HY_VERSION_MINOR 1
#define HY_VERSION_PATCH 3
#define HY_VERSION "0.1.3"

static const char *HY_LOGGER_PLUGIN_NAME = "hycore::plugin::logger::LoggerPlugin";

enum HyLoggerLevel
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus

{
  HY_LOGGER_LEVEL_TRACE,
  HY_LOGGER_LEVEL_DEBUG,
  HY_LOGGER_LEVEL_INFO,
  HY_LOGGER_LEVEL_WARN,
  HY_LOGGER_LEVEL_ERROR,
};
#ifndef __cplusplus
typedef uint32_t HyLoggerLevel;
#endif // __cplusplus

enum HyModuleCompileInfoFlagBits
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus

{
  HY_MODULE_COMPILE_INFO_FLAG_BITS_ENABLE_ZSTD_COMPRESSION = (1 << 0),
};
#ifndef __cplusplus
typedef uint32_t HyModuleCompileInfoFlagBits;
#endif // __cplusplus

enum HyStructureType
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus

{
  HY_STRUCTURE_TYPE_APPLICATION_INFO = 1,
  HY_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
  HY_STRUCTURE_TYPE_LOGGER_PLUGIN_CREATE_INFO,
  HY_STRUCTURE_TYPE_MODULE_COMPILE_INFO,
};
#ifndef __cplusplus
typedef uint32_t HyStructureType;
#endif // __cplusplus

typedef struct HyInstance HyInstance;

typedef struct
{
  uint16_t major;
  uint16_t minor;
  uint16_t patch;
} HyVersionInfo;

typedef struct
{
  HyStructureType sType;
  const char *pApplicationName;
  HyVersionInfo applicationVersion;
  const char *pEngineName;
  HyVersionInfo engineVersion;
} HyApplicationInfo;

typedef struct
{
  HyStructureType sType;
  const HyApplicationInfo *pApplicationInfo;
  uint64_t enabledPluginCount;
  const char *const *ppEnabledPlugins;
  uint64_t nodeRank;
  void *pNext;
} HyInstanceCreateInfo;

typedef struct
{
  const char *pData;
  uint32_t dataSize;
  const char *pFilename;
  uint32_t filenameSize;
} HyModuleCompileInfoSourceDescriptor;

typedef uint32_t HyModuleCompileInfoFlags;

typedef struct
{
  HyStructureType sType;
  const char *pBasePath;
  uint32_t basePathSize;
  const HyModuleCompileInfoSourceDescriptor *pSourceDescriptors;
  uint32_t sourceDescriptorCount;
  HyModuleCompileInfoFlags flags;
  void *pNext;
} HyModuleCompileInfo;

typedef uint64_t HyModule;

typedef struct
{
  int64_t timestamp;
  HyLoggerLevel level;
  const char *pMessage;
  const char *pFile;
  uint32_t line;
  const char *pModulePath;
  const char *pThreadName;
} HyLoggerRecord;

typedef void (*HyLoggerSinkCallback)(const HyLoggerRecord *pRecord, void *pUserData);

typedef struct
{
  HyStructureType sType;
  HyLoggerLevel level;
  HyLoggerSinkCallback pSinkCallback;
  void *pUserData;
  void *pNext;
} HyLoggerPluginCreateInfo;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void hyGetVersionInfo(HyVersionInfo *pVersionInfo);

int hyGetLastError(char *pBuffer,
                   uint32_t bufferSize,
                   char *pBacktraceBuffer,
                   uint32_t backtraceBufferSize);

int hyCreateInstance(const HyInstanceCreateInfo *pCreateInfo, HyInstance **ppInstance);

void hyDestroyInstance(HyInstance *pInstance);

int hyCompileModule(HyInstance *pInstance,
                    const HyModuleCompileInfo *pCompileInfo,
                    uint8_t **ppOutputBuffer,
                    uint32_t *pOutputBufferSize);

void hyFreeCompiledModuleBuffer(uint8_t *pBuffer);

int hyLoadCompiledModule(HyInstance *pInstance,
                         const uint8_t *pModuleBuffer,
                         uint32_t moduleBufferSize,
                         HyModule *pModule);

int hyDestroyModule(HyInstance *pInstance, HyModule module);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _HYCORE_H */
