/**
 * @file hycore.h
 * @brief Main C API header for Hyperion Core library.
 * @version 0.1.2
 *
 * This file header provides the C API for interacting with the Hyperion framework.
 * It was generated using cbindgen=0.28.0. DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is part of Hyperion.
 *
 * Copyright (C) 2024 Hyperion Project
 *
 * Hyperion is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Hyperion is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Hyperion. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef _HYCORE_H
#define _HYCORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define HY_VERSION_MAJOR 0
#define HY_VERSION_MINOR 1
#define HY_VERSION_PATCH 2
#define HY_VERSION "0.1.2"


typedef struct HyInstance HyInstance;

typedef struct
{
  uint16_t major;
  uint16_t minor;
  uint16_t patch;
} HyVersionInfo;

typedef struct
{
  const char *pApplicationName;
  HyVersionInfo applicationVersion;
  const char *pEngineName;
  HyVersionInfo engineVersion;
} HyApplicationInfo;

typedef struct
{
  const HyApplicationInfo *pApplicationInfo;
  uint64_t enabledPluginCount;
  const char *const *ppEnabledPlugins;
  uint32_t nodeRank;
  void *ext;
} HyInstanceCreateInfo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int hyCreateInstance(const HyInstanceCreateInfo *pCreateInfo, HyInstance **ppInstance);

void hyDestroyInstance(HyInstance *pInstance);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _HYCORE_H */
